update `AlignWith` to `EnforcedStyleAlignWith`
I am proposing this because your vueport gem imports from here and is currently failing with the latest rubocop

Error: obsolete parameter AlignWith (for Lint/EndAlignment) found in /Users/markburns/code/vueport/.rubocop-https---raw-githubusercontent-com-samtgarson-my-config-master--rubucop-yml